### ISSUE TITLE
deps: upgrade `minimatch` to v9 but it fails on some cases

### ISSUE THREAD

**Issue by JounQin** [un-es/eslint-plugin-import-x#22]
For anyone may be interested, I just upgraded `debug` to v4 and removed unused `resolve` dependencies at v2.29.1. And I tried to upgrade `minimatch` to v9 but it fails on some cases like

https://github.com/import-js/eslint-plugin-import/issues/2900#issuecomment-1859477364

and

https://github.com/import-js/eslint-plugin-import/blob/ee5fadeffff68f2300bed7f67a310496cb969d61/tests/src/rules/no-internal-modules.js

I don't have enough time to work on this replacement, anyone interested can help to raise a PR which will be appreciated.

---

For https://github.com/import-js/eslint-plugin-import/issues/2900#issuecomment-1859477364, I think it should be changed to `invalid` cases instead.

_Originally posted by @JounQin in https://github.com/un-es/eslint-plugin-i/issues/11#issuecomment-1859509446_

**Comment by SukkaW** [comment]
@JounQin Maybe try [`micromatch`](https://www.npmjs.com/package/micromatch) instead?

**Comment by JounQin** [comment]
@SukkaW It seems `minimatch` is better maintained than `micromatch`? Any benefit by using `micromatch` instead?
