### ISSUE TITLE
The future of this fork/plugin

### ISSUE THREAD

**Issue by JounQin** [un-es/eslint-plugin-import-x#24]
I'm thinking about maintaining this package as a complete independent plugin from upstream because a lot of issues can not be fixed easily without API changes, see

https://github.com/import-js/eslint-plugin-import/issues/1479

https://github.com/import-js/eslint-plugin-import/issues/2108

https://github.com/import-js/eslint-plugin-import/issues/2111

https://github.com/import-js/eslint-plugin-import/issues/2717

It would affect 3rd party resolvers like https://github.com/import-js/eslint-import-resolver-typescript/pull/248

@SukkaW do you want to collaborate here?

**Comment by 43081j** [comment]
when i was considering forking the same plugin, i came to the conclusion it makes more sense to diverge than staying in sync.

there's a lot of extra logic, architecture, etc that could easily fall away these days IMO.

i'd rather you make it independent so you can be set free on it rather than working within constraints of the original plugin

just my two cents

**Comment by JounQin** [comment]
Benefits

1. No limitations anymore, I'll rewrite the whole package with TypeScript, #23 can be fixed as an effect
2. Replace all the legacy codes to modern JavaScript/TypeScript
3. Add features we want

Downsides

1. Less contributors at the first place
2. Maybe difficult to support both plugins, what's the future of https://github.com/import-js/eslint-import-resolver-typescript
3. Per 2, should we support TypeScript as first-class, so basically we combined the two packages, is that worth or needed considering not everyone uses TypeScript and package size difference

**Comment by SukkaW** [comment]
eslint-plugin-import has been missing a **real** update for years. We should take this opportunity to drop all Node.js <= 14 support.

**Comment by JounQin** [comment]
> eslint-plugin-import has been missing a **real** update for years. We should take this opportunity to drop all Node.js <= 14 support.

@SukkaW 

Yes, we'll rewrite the whole code base into modern JavaScript/TypeScript features.

Do you want to join to maintain this project.

Next steps:

1. I'll transfer this repository into @un-ts org because it will be changed a TypeScript based library
2. If you want to join, which level do you want to be involved, org level or repository level
3. I'll start to setup the whole code base in a few days, the progress would just be similar as https://github.com/prettier/pretty-quick/compare/v3.1.3...v4.0.0

**Comment by 43081j** [comment]
a few things i think could be cleaned up or thrown away too:

- throw away memo-parser, feels like an experiment that got dumped in the repo and doesn't really belong here anymore
- eslint-module-utils is a "package" that gets pulled from disk (`utils/`), seems unnecessary. probably good to just move this stuff into `src/utils`
- check that those utils are actually needed
- consider dropping the concept of a "resolver"

i don't believe there's any need for this resolver architecture anymore. feels like an over-complication of things, especially splitting them out into independent packages.

i think you should be able to use this plugin and it supports every day resolution out of the box (standard resolution browsers/node-esm use, and node resolution). anything else is an edge case you could support through config, but definitely don't need an extra package for.

if we use enhanced-resolve, that itself is configurable for all those cases. doesn't seem to be a reason to have resolvers anymore, just configure enhanced-resolve differently for those edge cases.

**Comment by JounQin** [comment]
> i think you should be able to use this plugin and it supports every day resolution out of the box (standard resolution browsers/node-esm use, and node resolution). anything else is an edge case you could support through config, but definitely don't need an extra package for.

> if we use enhanced-resolve, that itself is configurable for all those cases. doesn't seem to be a reason to have resolvers anymore, just configure enhanced-resolve differently for those edge cases.

And that's why I'm using `enhanced-resolve` in https://github.com/import-js/eslint-import-resolver-typescript, I'll continue to use that package in the new core.

**Comment by Shinigami92** [comment]
Just want to leave my opinion here. I really like the idea of rewriting everything to TS and enhance the project in a good way.

Right now I don't feel like that I can over much time 🙁 
But if you want, you can invite me into the org 🙂 and I can help when I have and find time

Another thing: I dislike the plugin-name "i", because it is not clear what "i" means. Is it possible to e.g. publish as `@un-es/eslint-plugin-import` or something like that?

**Comment by JounQin** [comment]
The idea of `eslint-plugin-i` is coming from [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n).

**Comment by Shinigami92** [comment]
> The idea of `eslint-plugin-i` comes from [`eslint-plugin-n`](https://github.com/eslint-community/eslint-plugin-n).
> 
> Personally, I don't think we should rename to a new brand considering it's already a little bit well known.

I also hate `n`, what does "n" stand for? I would need to look this up in the Readme or Repo...

**Comment by JounQin** [comment]
> I also hate `n`, what does "n" stand for? I would need to look this up in the Readme or Repo...

I don't think anyone would use `@un-es/eslint-plugin-import` before knowing this is the active more elegant fork, I may prefer the use the non-fork version `eslint-plugin-import`.

`n` or `i` in another hand indicates it's much lightweight somehow. If you know what it does at once, you'll never forget it.

**Comment by 43081j** [comment]
i don't believe we need a resolver architecture/plugin system for that

nothing is stopping us providing configurable resolution using a single built-in resolver. i think it was an over-engineering of a much simpler thing. enhanced-resolve plus some configuration will achieve everything we need.

just my opinion though. sure you believed the opposite when you built it, which is fair enough. each to their own

**Comment by JounQin** [comment]
`enhanced-resolve` is good enough to handle webpack things.

**Comment by JounQin** [comment]
I've started the migration at #26

**Comment by fisker** [comment]
Really glad someone start fork it, I had really bad experience contribute to the original repo once, and decide never do it again..

>  I dislike the plugin-name "i".

Same here.

**Comment by JounQin** [comment]
Progress: I've successfully remove all `resolver` concept by using `enhanced-resolve` directly at [`f747071` (#26)](https://github.com/un-es/eslint-plugin-i/pull/26/commits/f747071a19d309426d97e9690183ef0107c93394) as @43081j proposed. And `eslint .` run in this project itself is just working, the next step will be focusing on testing.

**Comment by JounQin** [comment]
Do you think `@eslinter/eslint-plugin-import` or `@eslint-community/eslint-plugin-import` would be accepted?

I own @eslinter but I don't know how to join @eslint-community.

**Comment by 43081j** [comment]
doing such good work already 🙏  ill have a read through the PR this weekend if i can

on the naming - i do agree it'd be nice if it had a "full" name (rather than `i`) but i understand it already has a fair amount of users. if it were upto me, i'd probably call it `eslint-plugin-import` under a scope.

the eslint community org would be good to put this into but you're right that the scope is pretty lengthy. even if you don't adopt that name, it may still be worth joining that org on github though (assuming it is "official" and actively managed, and doesn't remove any ownership from you).

**Comment by fisker** [comment]
Any change to have [eslint-plugin-module](https://www.npmjs.com/package/eslint-plugin-module) or [eslint-plugin-modules](https://www.npmjs.com/package/eslint-plugin-modules)?

**Comment by Shinigami92** [comment]
`@eslint-community/eslint-plugin-import` would be nice, `@eslint-community` is a _trusted_ community group

**Comment by fisker** [comment]
Does `@eslint-community/eslint-plugin-import` even work in legacy ESLint config?

It should be `eslint-plugin-___` or `@___/eslint-plugin`, am I wrong? If it works, the plugin name will be `@eslint-community/import`?

**Comment by JounQin** [comment]
> Does @eslint-community/eslint-plugin-import even work in legacy ESLint config?

Yes. The users can always use the plugin full name or `@eslint-community/import` for shorthand.

**Comment by fisker** [comment]
```
{
   '@eslint-community/import/consistent-type-specifier-style': 'off'
}
```

Great rule name! 😄

**Comment by JounQin** [comment]
> Great rule name! 😄

That's why I'd prefer a short package name.

**Comment by JounQin** [comment]
Progress:

```log
Test Suites: 25 failed, 29 passed, 54 total
Tests:       257 failed, 2226 passed, 2483 total
```

**Comment by JounQin** [comment]
cc @MichaelDeBoey for @eslint-community

**Comment by MichaelDeBoey** [comment]
@JounQin Although I agree with the choices made in this fork and I don't get why @ljharb doesn't want to add them (I understand the reasoning of BC, but I don't agree with people still using Node v4, especially not for running their linter), I'm not sure if we want to have a fork of a package that's still actively maintained but has different opinions tbh 🤔

I'll talk to the rest of the core @eslint-community team to decide what to do with this case, as normally we're only taking over (widely dependent upon) ESLint-related packages that are either widely dependent upon and/or that are abandoned by the original author or where the original author wants to give it a safer place so it doesn't get abandoned if they're unable to continue maintenance for whatever reason

**Comment by ljharb** [comment]
fwiw I'm highly likely to do a breaking change i the first part of this year to drop eslint < 8, and the associated node versions.

**Comment by 43081j** [comment]
> I'm not sure if we want to have a fork of a package that's still actively maintained but has different opinions

choices are good. if it doesn't make sense to have two in the eslint-community org, maybe that's fair enough. but out in the wild, it'd be nice to see multiple options sometimes, regardless of why they exist. just fwiw.

i'm likely to move many repos to this plugin, away from the other, whatever the outcome of the naming and wherever it lives. some will be similar. so maybe the whole eslint-community thing is something for future rather than now (if it becomes depended upon enough).

**Comment by ljharb** [comment]
It def makes sense to wait until sufficient adoption before moving anything into that org.

**Comment by JounQin** [comment]
@MichaelDeBoey 

> I'm not sure if we want to have a fork of a package that's still actively maintained but has different opinions tbh

That's the biggest problem, a lot of issues can not be resolved due to this problem

> I'll talk to the rest of the core https://github.com/eslint-community team to decide what to do with this case

Glad to hear. And I want to clarify, we'll move forward w/wo joining in @eslint-community, and I own @eslinter, I'll migrate `eslnt-plugin-react` in next step.

---

@ljharb 

> fwiw I'm highly likely to do a breaking change i the first part of this year to drop eslint < 8, and the associated node versions.

Sorry, but I can't believe it and we've removed the concept of different `resolver`s, I don't think that's acceptable for you.

> It def makes sense to wait until sufficient adoption before moving anything into that org.

That's OK, we have our own org @eslinter.

**Comment by 43081j** [comment]
> I'll migrate `eslnt-plugin-react` in next step.

did you already start this? i have a branch lying around which does a bunch of it from what i remember

if you want any help, ping me when you make the repo and i'll push the branch for you to look at, at least

(don't want to take this thread off topic so lets catch up once the repo exists rather than here)

**Comment by ljharb** [comment]
@JounQin true, because that makes it useless for preach and svelte and vue and styled-components etc users.

**Comment by JounQin** [comment]
@43081j4I haven't personally, but I know a great project https://github.com/Rel1cx/eslint-react, that's why I said I really hope @Rel1cx can join us.

**Comment by Rel1cx** [comment]
> @43081j
> 
> I haven't personally, but I know a great project [Rel1cx/eslint-react](https://github.com/Rel1cx/eslint-react), that's why I said I really hope @Rel1cx can join us.

I strongly support you to do a full rewrite of eslnt-plugin-import, maybe called eslnt-plugin-esm + eslnt-plugin-cjs (two separate packages), or eslnt-plugin-module (one package).
But as for migrating eslint-plugin-react to eslint-plugin-jsx, my point of view is consistent with this reply https://github.com/Rel1cx/eslint-react/issues/52#issuecomment-1785153861.

**Comment by JounQin** [comment]
@Rel1cx In my view, some rules are universal, some rules are framework specific.

For react rules, we can have `jsx/react-x` rules, for vue rules, we can have `jsx/vue-x` rules, etc.

So in `eslint-plugin-jsx`, @eslint-react could be an dependency.

**Comment by Rel1cx** [comment]
You could make an eslint-plugin-jsx but that only makes sense if the rules in it are truly framework-agnostic, and considering that most of the natural framework-agnostic rules have already been migrated to @stylistic/eslint-plugin-jsx, there aren't that many left.

Where JSX fits into the ecosystem of front-end languages and frameworks:

JS in Vue
TS in Vue
TSX in Vue

JS in Solid
TS in Solid
TSX in Solid

...

In essence, JSX is just a syntax extension, how to lint TSX here is the same as TS, JS here, it's up to the frameworks, making an eslint-plugin-jsx that doesn't just take care of the correctness of JSX itself, but also has to be configured (or prefixed) to support the behaviour of all the specific frameworks that have used JSX in the past, are using JSX now, and will be in the future **is equivalent to making a @typescript-eslint/eslint-plugin but not only for the correctness of TS itself but also configured (or prefixed) to support the behaviour of all the frameworks that use TS, React, Preact, Solid, Vue, etc**.

**Comment by 43081j** [comment]
Just my two cents, I roughly agree.

- there should be a jsx plugin which lints jsx syntax (similar to a html validator), but nothing framework specific
- there should be a plugin for each framework with the framework specific rules, whether using jsx or not

**Comment by JounQin** [comment]
OK, like @jsx-eslint, I own @eslint-jsx, we can make framework specific plugins at that org.

**Comment by JounQin** [comment]
Progress:

```log
Test Suites: 21 failed, 33 passed, 54 total
Tests:       171 failed, 2108 passed, 2279 total
```

**Comment by JounQin** [comment]
After thinking, I think [`eslint-plugin-import-x`](https://www.npmjs.com/package/eslint-plugin-import-x) could be the best choice just like https://github.com/eslint-community/eslint-plugin-es-x.

**Comment by 43081j** [comment]
i think that makes sense, since future forks of other plugins could follow the same naming convention too. nice to have some consistency there

**Comment by JounQin** [comment]
I've published [eslint-plugin-import-x](https://www.npmjs.com/package/eslint-plugin-import-x) as the successor of `eslint-plugin-i`, it should work as previous for now, except it's not an alias anymore, all settings are renamed into `import-x/` prefix.

The whole progress was tough, #26 was unable to continue because I chose to migrate codes instead tests first.

But finally I migrated `babel-core` into `@babel/core`, `babel-eslint` into `@babel/eslint-parser`, etc., successfully at #30. And I also migrated `mocha`/`sinon` to `jest`.

But I haven't removed the `resolver` concept: let's continue discussing at #40.

---

In the next step, I'll try to migrate the whole code base into TypeScript.

**Comment by dirkluijk** [comment]
Just wanted to leave my appreciation here in this thread for this awesome fork.
Thanks for all the work from all contributors. ❤️

**Comment by melroy89** [comment]
Me too! I would like to thank all the contributors (a shout out to: @SukkaW, @stepankuzmin, @marcalexiei and @baevm).

Thank you all for the latest version with ESLint v10 support. This was the last package I needed to upgrade my full stack to Eslint v10 🥳 .

**Comment by MichaelDeBoey** [comment]
It's interesting to look back at this discussion now, especially given the recent ESLint TSC discussions around the maintenance of widely used plugins.

At the time, the decision to maintain `eslint-plugin-import-x` independently made a lot of sense.
The goal was to modernize the codebase, move to TypeScript and avoid being constrained by the architecture and APIs of `eslint-plugin-import`.

Fast-forward to today and I think this project has become a good example of why having an actively maintained, community-driven home for widely depended-upon ESLint packages can be valuable.

The ESLint Technical Steering Committee (TSC) recently discussed concerns around popular plugins not keeping up with ESLint v10 and whether such plugins should be maintained under the official [`@eslint-community` organization](https://github.com/eslint-community).

In that context, we've opened #510 about potentially moving `eslint-plugin-import-x` to the @eslint-community org.

I think that could be a natural continuation of the original goal of this project: keeping the plugin independently maintained and allowing it to evolve without being held back by the maintenance situation of the original `eslint-plugin-import`.

For reference:

- [TSC discussion](https://discord.com/channels/688543509199716507/688545247843713092/1545165081246048386)
- [TSC meeting agenda item](https://github.com/eslint/tsc-meetings/issues/749#issuecomment-5453881630)
- [Invitation to move `eslint-plugin-import-x` to @eslint-community](https://github.com/un-ts/eslint-plugin-import-x/issues/510)
